version: '3.8'

services:
  outline-agent:
    build:
      context: .
      dockerfile: Dockerfile.single
    container_name: outline-agent
    ports:
      - "80:80"      # Nginx proxy
      - "3000:3000"  # Outline dev server (direct access)
      - "6080:6080"  # VNC web client
      - "5900:5900"  # Direct VNC access
      - "5432:5432"  # PostgreSQL (for external tools)
      - "6379:6379"  # Redis (for external tools)
    volumes:
      # Persistent data only (source code is in container)
      - outline-data:/var/lib/outline/data
      - postgres-data:/var/lib/postgresql/16/main
      - redis-data:/var/lib/redis
      # Screenshots directory for agent
      - screenshots:/home/outline/screenshots
    environment:
      # Production environment variables
      - NODE_ENV=production
      - SECRET_KEY=development-secret-key-not-for-production
      - UTILS_SECRET=development-utils-secret-not-for-production
      - URL=http://localhost:3000
      - DEBUG=cache,presenters,events,emails,mailer,utils,multiplayer,server,services
      - LOG_LEVEL=debug
      - DEVELOPMENT_UNSAFE_INLINE_CSP=true
      - DISPLAY=:1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Longer start period for development
    # Allow container to access host for development tools
    network_mode: bridge
    # Add capabilities for development debugging
    cap_add:
      - SYS_PTRACE
    # Keep container running even if main process fails (for debugging)
    tty: true
    stdin_open: true

volumes:
  outline-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  screenshots:
    driver: local